version: '3.7'
services:
  visdom-composer:
    container_name: visdom-composer
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - COMPOSER_ASSETPATH
        - COMPOSER_BASENAME
    ports:
      - '9071:80'
